/** Country codes for registration (value stored on profile) */
export const COUNTRY_OPTIONS = [
  { value: "USA", label: "United States" },
  { value: "CAN", label: "Canada" },
  { value: "GBR", label: "United Kingdom" },
  { value: "AUS", label: "Australia" },
  { value: "DEU", label: "Germany" },
  { value: "FRA", label: "France" },
  { value: "ITA", label: "Italy" },
  { value: "ESP", label: "Spain" },
  { value: "MEX", label: "Mexico" },
  { value: "BRA", label: "Brazil" },
  { value: "IND", label: "India" },
  { value: "CHN", label: "China" },
  { value: "JPN", label: "Japan" },
  { value: "KOR", label: "South Korea" },
  { value: "NLD", label: "Netherlands" },
  { value: "BEL", label: "Belgium" },
  { value: "CHE", label: "Switzerland" },
  { value: "AUT", label: "Austria" },
  { value: "SWE", label: "Sweden" },
  { value: "NOR", label: "Norway" },
  { value: "DNK", label: "Denmark" },
  { value: "FIN", label: "Finland" },
  { value: "IRL", label: "Ireland" },
  { value: "NZL", label: "New Zealand" },
  { value: "SGP", label: "Singapore" },
  { value: "ARE", label: "United Arab Emirates" },
  { value: "ZAF", label: "South Africa" },
  { value: "PHL", label: "Philippines" },
  { value: "OTHER", label: "Other" },
] as const;
